config/routes.rb
AppRails::Application.routes.draw do
  root :to => "clients#index"
  resources :spares
  resources :works
  resources :slists
  resources :clients
  resources :autos
  resources :cautos
  resources :orders
  resources :olists
  resources :warehouses
  resources :flags
  resources :orderspares

end

app/models/auto.rb
class Auto < ActiveRecord::Base
  has_many :cautos
  attr_accessible :name
end

app/models/cauto.rb
class Cauto < ActiveRecord::Base
  belongs_to :auto
  belongs_to :user
  has_many :orders
  attr_accessible :auto_id, :client_id, :mileage, :year

  def name
    return auto.name
  end
end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :addres, :name, :phone
  has_many :cautos
  has_many :orders
end

app/models/flag.rb
class Flag < ActiveRecord::Base
  attr_accessible :name
  has_many :orderspares
end

app/models/olist.rb
class Olist < ActiveRecord::Base
  attr_accessible :order_id, :slist_id

  belongs_to :order
  belongs_to :slist

  def name
    return slist.work.name
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :cauto_id, :client_id
  belongs_to :cauto
  belongs_to :client
  has_many :olists

  def ressum
    return olists.sum { |o| o.slist.ressum }
  end

end

app/models/orderspare.rb
class Orderspare < ActiveRecord::Base
  attr_accessible :count, :spare_id, :flag_id, :warehouse_id
  belongs_to :spare
  belongs_to :warehouse
  belongs_to :flag
end

app/models/slist.rb
class Slist < ActiveRecord::Base
  belongs_to :spare
  belongs_to :work
  has_many :olists
  attr_accessible :count, :spare_id, :work_id

  def name
    return work.name
  end

  def ressum
    return spare.price * count
  end
end

app/models/spare.rb
class Spare < ActiveRecord::Base
  attr_accessible :description, :name, :price
  has_many :slists
  has_many :orderspares
  #has_many :works, :through => :slists

  def count_of_warehouse
    inp = orderspares.where(:flag_id => 2).sum { |o| o.count }
    out = orderspares.where(:flag_id => 3).sum { |o| o.count }
    return inp - out
  end
end

app/models/warehouse.rb
class Warehouse < ActiveRecord::Base
  attr_accessible :name
  has_many :orderspares
end

app/models/work.rb
class Work < ActiveRecord::Base
  attr_accessible :name
  has_many :slists
  #has_many :spares, :through => :slists
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def show
    @client = Client.find(params[:id])
  end

  def create
    order = Order.new(params[:order])
    if order.save
      redirect_to order_path(order.client_id)
    end
  end

  def edit
    @order = Order.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/autos_helper.rb
module AutosHelper
end

app/helpers/cautos_helper.rb
module CautosHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/flags_helper.rb
module FlagsHelper
end

app/helpers/olists_helper.rb
module OlistsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/slists_helper.rb
module SlistsHelper
end

app/helpers/spares_helper.rb
module SparesHelper
end

app/helpers/warehouses_helper.rb
module WarehousesHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/orders/edit.html.erb
<h1>Заказ</h1>

<%= form_for Olist.new do |f| %>
<div class="field">
  Модель
  <%= collection_select(:olist, :slist_id, Slist.all, :id, :name) %>
  <%= f.hidden_field :order_id, :value => @order.id %>
  <%= f.submit "Add" %>
</div>
<% end %>
<br/>

<table>
<tr>
  <th>Действие</th>
  <th></th>
</tr>
<% @order.olists.each do |f| %>
<tr>
  <td><%= f.name %></td>
  <td><%= link_to "Delete", olist_path(@order, f.id), :confirm => 'Are you sure?', :method => :delete%></td>
</tr>

<% end %>
<tr>
  <td>Сумма</td>
  <td><%= @order.ressum %></td>
</tr>
</table>

app/views/orders/show.html.erb
<div>
  <%= link_to "Автомобили", cauto_path(params[:id])%>
  <%= link_to "Заказы", order_path(params[:id]) %>
</div>

<%= form_for Order.new do |f| %>
<div class="field">
  Модель
  <%= collection_select(:order, :cauto_id, @client.cautos, :id, :name) %>
  <%= f.hidden_field :client_id, :value => params[:id] %>
  <%= f.submit "Add" %>
</div>
<% end %>
<br/>

<table>
<tr>
  <th>Модель</th>
  <th>Дата</th>
  <th></th>
</tr>
<% @client.orders.each do |f| %>
<tr>
  <td><%= f.cauto.name %></td>
  <td><%= f.created_at %></td>
  <td><%= link_to "Edit", edit_order_path(f.id) %></td>
</tr>
<% end %>
</table>