config/routes.rb
AppRails::Application.routes.draw do
  root :to => "clients#index"
  resources :spares
  resources :works
  resources :slists
  resources :clients
  resources :autos
  resources :cautos
  resources :orders
  resources :olists
  resources :warehouses
  resources :flags
  resources :orderspares

end

app/models/auto.rb
class Auto < ActiveRecord::Base
  has_many :cautos
  attr_accessible :name
end

app/models/cauto.rb
class Cauto < ActiveRecord::Base
  belongs_to :auto
  belongs_to :user
  has_many :orders
  attr_accessible :auto_id, :client_id, :mileage, :year

  def name
    return auto.name
  end
end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :addres, :name, :phone
  has_many :cautos
  has_many :orders
end

app/models/flag.rb
class Flag < ActiveRecord::Base
  attr_accessible :name
  has_many :orderspares
end

app/models/olist.rb
class Olist < ActiveRecord::Base
  attr_accessible :order_id, :slist_id

  belongs_to :order
  belongs_to :slist

  def name
    return slist.work.name
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :cauto_id, :client_id
  belongs_to :cauto
  belongs_to :client
  has_many :olists

  def ressum
    return olists.sum { |o| o.slist.ressum }
  end

end

app/models/orderspare.rb
class Orderspare < ActiveRecord::Base
  attr_accessible :count, :spare_id, :flag_id, :warehouse_id
  belongs_to :spare
  belongs_to :warehouse
  belongs_to :flag
end

app/models/slist.rb
class Slist < ActiveRecord::Base
  belongs_to :spare
  belongs_to :work
  has_many :olists
  attr_accessible :count, :spare_id, :work_id

  def name
    return work.name
  end

  def ressum
    return spare.price * count
  end
end

app/models/spare.rb
class Spare < ActiveRecord::Base
  attr_accessible :description, :name, :price
  has_many :slists
  has_many :orderspares
  #has_many :works, :through => :slists

  def count_of_warehouse
    inp = orderspares.where(:flag_id => 2).sum { |o| o.count }
    out = orderspares.where(:flag_id => 3).sum { |o| o.count }
    return inp - out
  end
end

app/models/warehouse.rb
class Warehouse < ActiveRecord::Base
  attr_accessible :name
  has_many :orderspares
end

app/models/work.rb
class Work < ActiveRecord::Base
  attr_accessible :name
  has_many :slists
  #has_many :spares, :through => :slists
end

app/controllers/orderspares_controller.rb
class OrdersparesController < ApplicationController
  def show
    @spare = Spare.all
    @flag = Flag.find(1)
    @warehouse = Warehouse.find(params[:id]).orderspares
  end

  def create
    order = Orderspare.new(params[:orderspare])
    if order.save
      redirect_to orderspare_path(order.warehouse_id)
    else
      redirect_to orderspare_path(params[:warehouse_id])
    end
  end

  def edit
    @flag = Flag.all
    @spare = Spare.all
    @orderspare = Orderspare.find(params[:id])
  end

  def update
    @orderspare = Orderspare.find(params[:id])
    if @orderspare.update_attributes(params[:orderspare])
      redirect_to orderspare_path(@orderspare.warehouse_id)
    end
  end
end

app/helpers/autos_helper.rb
module AutosHelper
end

app/helpers/cautos_helper.rb
module CautosHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/flags_helper.rb
module FlagsHelper
end

app/helpers/olists_helper.rb
module OlistsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/orderspares_helper.rb
module OrdersparesHelper
end

app/helpers/slists_helper.rb
module SlistsHelper
end

app/helpers/spares_helper.rb
module SparesHelper
end

app/helpers/warehouses_helper.rb
module WarehousesHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/orderspares/edit.html.erb
<h1>Заявка - <%= @orderspare.spare.name %></h1>
<%= form_for(@orderspare) do |f| %>
<div class="field">
  <%= f.label "Расхоный материал" %>
  <%= collection_select(:orderspare, :spare_id, @spare, :id, :name) %>
</div>
<div class="field">
  <%= f.label :count %>
  <%= f.text_field :count %>
</div>
<div class="field">
  <%= f.label "Статус" %>
  <%= collection_select(:orderspare, :flag_id, @flag, :id, :name) %>
</div>
<div class="actions">
  <%= f.submit "Update" %>
</div>
<% end %>

app/views/orderspares/show.html.erb
<h1>Оформить заявку</h1>
<%= form_for Orderspare.new do |f| %>
<div class="field">
  <%= f.label "Расходный материал" %>
  <%= collection_select(:orderspare, :spare_id, @spare, :id, :name) %>
</div>
<div class="field">
  <%= f.label :count %>
  <%= f.text_field :count %>
  <%= f.hidden_field :flag_id, :value => @flag.id %>
  <%= f.hidden_field :warehouse_id, :value => params[:id] %>
</div>

<div class="action">
  <%= f.submit "Add" %>
</div>
<% end %>
<br/>
<h1>Заявки</h1>
<table>
<tr>
  <th>id</th>
  <th>Материал</th>
  <th>Количество</th>
  <th>Статус</th>
  <th></th>
</tr>
<% @warehouse.each do |f| %>
<tr>
  <td><%= f.id %></td>
  <td><%= f.spare.name %></td>
  <td><%= f.count %></td>
  <td><%= f.flag.name %></td>
  <td><%= link_to "Edit", edit_orderspare_path(f.id) %></td>
</tr>
<% end %>
</table>